### ISSUE TITLE
License expiration reminder & license expired email is send twice

### ISSUE THREAD

**Issue by jorenvh** [spatie/spatie.be#141] opened 2021-01-31 10:21 UTC
I received both the reminder & de license expired email for my Mailcoach license twice. Both emails where delivered at the same time. 

I took a quick look in the console command but at first glance I can not spot an issue there. Maybe there is some sort of duplicate record from the time before everything was managed through the spatie.be website? My license was purchased from the Mailcoach website, a few days after it launched.

Let me know if there is anything else that I can provide to help resolve this issue.

![Screenshot 2021-01-31 at 11 16 43](https://user-images.githubusercontent.com/8791625/106380936-ce853980-63b5-11eb-9fea-1a3ecbff0f9c.png)

**Comment by freekmurze** [comment] 2021-01-31 11:51
Looking at your screenshot you got the expired license mail twice (and not the reminder).

In our database there's only one record with your email.

It shows these timestamps: 
<img width="339" alt="image" src="https://user-images.githubusercontent.com/483853/106382903-e1523b00-63c2-11eb-89f0-96cfcdc5c697.png">

So the reminder should have been sent earlier, could you check that. I haven't figured out yet why you got the expired mail twice.

**Comment by freekmurze** [comment] 2021-01-31 11:54
Could you forward me the two mails you got?

**Comment by jorenvh** [comment] 2021-01-31 14:00
The reminder was send twice as well. I will forward all 4 emails to you. 

![image](https://user-images.githubusercontent.com/8791625/106386359-e15b3680-63d4-11eb-9a03-c0cb6c22a2aa.jpeg)

**Comment by freekmurze** [comment] 2021-04-13 18:15
We've received no other complaints, I can't reproduce this, so I'm thinking this is something that was caused by specific conditions when mails for your account were sent.

Closing for now.

**Closed by freekmurze** 2021-04-13 18:15 UTC
